### ISSUE TITLE
Incorrect parsing of aircrafttype in some departures

### ISSUE THREAD

**Issue by mnemocron** [dxmekch/ZRHSpotterTool#3]
Note the "e"

```json
{
    "airportinformation": {
        "airport_city": "COLOGNE"
    },
    "expected": "",
    "flightcode": "NJE 930",
    "masterflight": {
        "aircrafttype": "e",
        "registration": "CSDUB"
    },
    "scheduled": "18:00",
    "status": ""
}
```

**Comment by mnemocron** [comment]
type is empty on website as well.
workaround,
`if(type == "e"): type = ""`

**Comment by dxmekch** [comment]
this error occurs because the web developer of zrh forgot to add the ":" on the departures table. 🙃 

can be either ignored while stripping the homepage (back end) or while parsing the json (front end).
